[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CEINMS"
authors = [{name = "Jochem", email = "jochem.vado@gmail.com"}]
dynamic = ["version", "description"]
