[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CEINMS-RT documentation"
authors = [{name = "CEINMS-RT", email = "m.sartori@utwente.nl"}]
dynamic = ["version", "description"]
